### ISSUE TITLE
Syntax validation and test seems to not work

### ISSUE THREAD

**Issue by shlomi-nx** [casbin/editor#1]
Does not matter what appears in the text boxes, it always claims there are no errors and that the "test pass"

![Screen Shot 2019-03-20 at 2 52 15 PM](https://user-images.githubusercontent.com/39283673/54721708-e6d07000-4b1f-11e9-827a-7df88f27f07c.png)

**Comment by hsluoyz** [comment]
As you see, those buttons don't work yet. It's still in progress.

**Comment by shlomi-nx** [comment]
Thanks for replying. I guess it would be better to have the buttons either say "Work in progress" rather than "No Error!", or even better, hide the buttons until the functionality is ready.

I spent 15 minutes messing around thinking it is validating my input. Only when I made an obvious mistake did I notice it wasn't actually doing anything.

**Comment by hsluoyz** [comment]
Hi @shlomi-nx , sorry for the misleading. We have started to add a simple and primitive syntax validation via [this commit](https://github.com/casbin/editor/commit/15b2a5f36b66ae460639fc512e58558dc0bcb66a), please try it at: https://casbin.org/editor/

**Comment by hsluoyz** [comment]
Hi @shlomi-nx , we have redone our editor: https://casbin.org/en/editor

**Comment by shlomi-nx** [comment]
Beautifully done!
