### ISSUE TITLE
policy_effect validator does not detect unacceptable syntax

### ISSUE THREAD

**Issue by shlomi-nx** [casbin/editor#3]
If you put 
```ini
[policy_effect]
e = some(whe re (p.eft == allow))
# note the  ^  space inside the `where` 
```

the validator claims that it is valid.

For now, I believe the only way to truly validate this portion is by making sure the string for `e` is exactly one of the four allowed strings (including spaces), as discussed here https://github.com/casbin/casbin/issues/211

**Comment by hsluoyz** [comment]
@nodece

**Comment by nodece** [comment]
Hi @shlomi-nx ,  added policy effect validator to editor.
